ShauliBlogProject/Models/SeggPost.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShauliBlogProject.Models
{
    public class SeggPost
    {
        public int ID { get; set; }
        public string ByAuthor { get; set; }
        public int Count { get; set; }
    }
}

ShauliBlogProject/Controllers/BlogController.cs
using ShauliBlogProject.DAL;
using ShauliBlogProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Facebook;
using Microsoft.AspNet.Identity;
using Accord.MachineLearning.VectorMachines.Learning;
using Accord.Statistics.Kernels;

namespace ShauliBlogProject.Controllers
{
    public class BlogController : Controller
    {
        private ApplicationDbContext dbUsers = new ApplicationDbContext();
        private ShauliBlogContext db = new ShauliBlogContext();
        private const int PostPerPage = 4;

        public ActionResult Index(int? id)
        {
            var userId = User.Identity.GetUserId();
            if (userId != null)
            {
                int i = db.Posts.Count();
                double[][] inputs = new double[i][];
                int[] outputs = new int[i];
                int j = 0;

                var types = db.UserTypes.Where(x => x.UserID == userId);

                foreach (var n in types)
                {
                    var ID = n.PostID;
                    PostType type = db.Types.Where(x => x.PostTypeID == ID).First();

                    inputs[j] = new double[5];

                    //inputs[j] = type.getTypeArray();
                    inputs[j][0] = type.Sport;
                    inputs[j][1] = type.Music;
                    inputs[j][2] = type.Food;
                    inputs[j][3] = type.Vacation;
                    inputs[j][4] = type.Study;

                    outputs[j] = n.Visit;
                    j++;
                }

                var teacher = new SequentialMinimalOptimization<Gaussian>()
                {
                    UseComplexityHeuristic = true,
                    UseKernelEstimation = true // estimate the kernel from the data
                };

                // Teach the vector machine
                var svm = teacher.Learn(inputs, outputs);
                //Get all posts
                var _posts = (from p in db.Posts select p);
                //New list for login customer
                List<Post> SVMPosts = new List<Post>();
                foreach (var p in _posts)
                {                    
                    bool answer = svm.Decide(p.Types.getTypeArray());
                    if (answer)
                    {
                        SVMPosts.Insert(0, p);
                    } else
                    {
                        SVMPosts.Add(p);
                    }
                }
                return View(SVMPosts);
            }

            int pageNumber = id ?? 0;
            IEnumerable<Post> posts =
                (from post in db.Posts
                 where post.postDate < DateTime.Now
                 orderby post.postDate descending
                 select post).Skip(pageNumber * PostPerPage).Take(PostPerPage + 1);
            ViewBag.IsPreviousLinkVisible = pageNumber > 0;
            ViewBag.IsNextLinkVisible = posts.Count() > PostPerPage;
            ViewBag.PageNumber = pageNumber;
            ViewBag.IsAdmin = IsAdmin;
            return View(posts.Take(PostPerPage));
        }

        [HttpPost]
        public ActionResult Index(int? id, string dateSearch, string authorSearch, string emailSearch, string wordsSearch)
        {
            var segg = db.SeggPosts.Where(l => l.ByAuthor == authorSearch);
            if(segg.Count() == 0)
            {
                var seg = new SeggPost { ByAuthor = authorSearch, Count = 1 };
                db.SeggPosts.Add(seg);
                db.SaveChanges();
            }
            else
            {
                segg.First().Count++;
                db.SaveChanges();
            }

            var result = (from post in db.Posts select post);

            if (!String.IsNullOrEmpty(dateSearch))
            {
                DateTime date = DateTime.Parse(dateSearch);
                result = result.Where(x => x.postDate >= date);
            }
            if (!String.IsNullOrEmpty(authorSearch))
            {
                result = result.Where(x => x.Author.Contains(authorSearch));
            }
            if (!String.IsNullOrEmpty(emailSearch))
            {
                result = result.Where(x => x.url_author_post.Contains(emailSearch));
            }
            if (!String.IsNullOrEmpty(wordsSearch))
            {
                result = result.Where(x => x.contentPost.Contains(wordsSearch));
            }

            ViewBag.IsAdmin = IsAdmin;
            return View(result);
        }

        //[Authorize(Roles = "Admins")]
        public ActionResult details(int id)
        {
            var userId = User.Identity.GetUserId();
            if (userId != null)
            {
                var types = db.UserTypes.Where(x => x.UserID == userId);
                UserType userType = types.Where(x => x.PostID == id).First();
                userType.Visit = 1;
                db.SaveChanges();
            }

            Post post = GetPost(id);
            ViewBag.IsAdmin = IsAdmin;
            return View(post);
        }

        [Authorize(Roles = "Admins")]
        [ValidateInput(false)]
        public ActionResult Update(int? PostID, string Title, string Author, string url_author_post, DateTime postDate, string contentPost, string image, string video, int food = 0, int sport = 0, int vacation = 0, int study = 0, int music = 0)
        {
            if (!String.IsNullOrEmpty(Title) && !String.IsNullOrEmpty(Author) && !String.IsNullOrEmpty(url_author_post) && !String.IsNullOrEmpty(contentPost))
            {
                Post post = GetPost(PostID);
                post.Title = Title;
                post.Author = Author;
                post.url_author_post = url_author_post;
                post.postDate = postDate;
                post.contentPost = contentPost;
                post.image = image;
                post.video = video;

                PostType type;
                if (!PostID.HasValue)
                {
                    type = new PostType();
                }
                else
                {
                    type = db.Types.Where(x => x.PostTypeID == PostID).First();
                }

                type.Food = food;
                type.Sport = sport;
                type.Vacation = vacation;
                type.Study = study;
                type.Music = music;
                type.Post = post;
                post.Types = type;

                if (!PostID.HasValue)
                {
                    db.Posts.Add(post);
                    db.Types.Add(type);
                }

                try
                {
                    PostToWall(post, 10205420130967215, "EAACEdEose0cBAIGOHy0TQOLDzWvpFK5CzEieFmMwAax4imOWP9UtSAmNpdwolcYWnDG4Nb9RVcIRUzoAIHET9ZCaB4hN4CPxFi42jnEnYWvjZBxROFtYw9GJXTZC1bzXehTaOXGuGx6ZBPvW6XnZBd0dngTImn4tTYwfWDWyFrjrMEjYXSYRoyNegzFmZCEZCcZD");
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                }

                db.SaveChanges();

                if (!PostID.HasValue)
                {
                    foreach (var u in dbUsers.Users)
                    {
                        UserType userType = new UserType();
                        userType.UserID = u.Id;
                        userType.PostID = post.PostID;
                        userType.Visit = 0;
                        db.UserTypes.Add(userType);
                    }
                    db.SaveChanges();
                }
                return RedirectToAction("Details", new { id = post.PostID });
            }
            return RedirectToAction("Edit", new { id = PostID });
        }

        [ValidateInput(false)]
        public ActionResult Comment(int id, string Title, string Author, string url_author_comment, string content_comment)
        {
            Post post = GetPost(id);
            Comment comment = new Comment();
            comment.post = post;
            comment.Title = Title;
            comment.Author = Author;
            comment.url_author_comment = url_author_comment;
            comment.content_comment = content_comment;
            db.Comments.Add(comment);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admins")]
        public ActionResult Edit(int? id)
        {
            Post post = GetPost(id);
            if (id.HasValue)
            {
                PostType type = db.Types.Where(x => x.PostTypeID == id).First();
                ViewBag.vFood = Convert.ToBoolean(type.Food);
                ViewBag.vSport = Convert.ToBoolean(type.Sport);
                ViewBag.vVacation = Convert.ToBoolean(type.Vacation);
                ViewBag.vStudy = Convert.ToBoolean(type.Study);
                ViewBag.vMusic = Convert.ToBoolean(type.Music);
            }
            return View(post);
        }

        [Authorize(Roles = "Admins")]
        public ActionResult Delete(int id)
        {
            if (User.IsInRole("Admins"))
            {
                IQueryable<UserType> userTypes = db.UserTypes.Where(x => x.PostID == id);
                foreach(var userType in userTypes)
                {
                    db.UserTypes.Remove(userType);
                }
                PostType postType = db.Types.Where(x => x.PostTypeID == id).First();
                db.Types.Remove(postType);
                Post post = GetPost(id);
                db.Posts.Remove(post);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admins")]
        public ActionResult DeleteComment(int id)
        {
            if (User.IsInRole("Admins"))
            {
                Comment comment = db.Comments.Where(x => x.CommentID == id).First();
                db.Comments.Remove(comment);
                db.SaveChanges();
            }

ShauliBlogProject/Controllers/MapsController.cs
using ShauliBlogProject.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GoogleMaps.LocationServices;

namespace ShauliBlogProject.Controllers
{
    public class MapsController : Controller
    {
        private ShauliBlogContext db = new ShauliBlogContext();

        public class Marker
        {
            public double x;
            public double y;
        };

        public ActionResult About()
        {
            var Map = (from m in db.Maps select m);
            var count = Map.Count();
            Marker[] markersArrayOffice = new Marker[count];
            int z = 0;

            for (int i = 0; i < markersArrayOffice.Length; i++)
                markersArrayOffice[i] = new Marker();
            try
            {
                foreach (var Item in Map)
                {
                    string FullAddress = Item.Address.ToString() + ", " + Item.City.ToString() + ", " + Item.Country.ToString();
                    var locationService = new GoogleLocationService();
                    var point = locationService.GetLatLongFromAddress(FullAddress);
                    markersArrayOffice[z].x = point.Latitude;
                    markersArrayOffice[z].y = point.Longitude;
                    z++;
                }

                ViewBag.markersArrayOffice = markersArrayOffice;

                var FansMap = (from u in db.Maps
                               join b in db.FansClub
                               on u.Country equals b.Country
                               select new { b.Country, b.City, b.Address });

                count = FansMap.Count();
                Marker[] markersArray = new Marker[count];
                for (int i = 0; i < markersArray.Length; i++)
                    markersArray[i] = new Marker();

                z = 0;
                foreach (var Item in FansMap)
                {
                    string FullAddress = Item.Address.ToString() + ", " + Item.City.ToString() + ", " + Item.Country.ToString();
                    var locationService = new GoogleLocationService();
                    var point = locationService.GetLatLongFromAddress(FullAddress);
                    markersArray[z].x = point.Latitude;
                    markersArray[z].y = point.Longitude;
                    z++;
                }

                ViewBag.markersArray = markersArray;

                return View();
            }
            catch (Exception ex) {}
            return PartialView("_mapError");
        }
    }
}

ShauliBlogProject/Controllers/TreeController.cs
using Newtonsoft.Json;
using ShauliBlogProject.DAL;
using ShauliBlogProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShauliBlogProject.Controllers
{
    public class TreeController : Controller
    {
        private ShauliBlogContext db = new ShauliBlogContext();
        private string vjson;
        private int vid;

        public ActionResult TreeGenerate()
        {
            ViewBag.json = "Posts.xml";
            ViewBag.id = vid;

            return View();
        }

        public ActionResult PostTreeD3()
        {

            IEnumerable<SelectListItem> posts = db.Posts.Select(p => new SelectListItem { Value = p.PostID.ToString(), Text = p.Title });
            ViewBag.Posts = posts;

            return View();
        }
        [HttpPost]
        public ActionResult PostTreeD3(int PostID)
        {

            Post p = db.Posts.Where(x => x.PostID == PostID).First();
            postTree posttree = new postTree(p);

            string json = JsonConvert.SerializeObject(posttree);
            var MapPath = System.Web.Hosting.HostingEnvironment.MapPath("~/Files/Posts.xml");
            System.IO.File.WriteAllText(MapPath, json);

            //ViewBag.json = "Posts.xml";
            //ViewBag.id = PostID;

            vjson = "Posts.xml";
            vid = PostID;

            return RedirectToAction("TreeGenerate");
        }
        public class postTree
        {
            public string name { get; set; }
            public List<commentTree> children { get; set; }
            public postTree(Post p)
            {
                this.name = p.Title;
                this.children = new List<commentTree>();
                foreach (var c in p.comments)
                {
                    this.children.Add(new commentTree(c.Author));
                }
            }
        }
        public class commentTree
        {
            public string name { get; set; }

            public commentTree(string title)
            {
                this.name = title;
            }
        }
    }
}

ShauliBlogProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shauli's Blog</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <!--Header-->
    <div class="container">
        <div class="page-header">
            <h2>Shauli's Blog</h2>
        </div>
    </div>
    <!--Navbar-->
    <div class="navbar navbar-inverse navbar-fixed">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Shauli's Blog", "Index", "Blog", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Blog", "Index", "Blog")</li>
                    <li>@Html.ActionLink("Fan Club", "Index", "FansClubs")</li>
                    <li>
                        <div id="transDemo2">
                            <div class="hover">
                                <img src="/images/rss.png" width="30" height="30">
                            </div>
                        </div>
                    </li>
                    <li><a href="#">Subscribe via. RSS</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">More <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">@Html.ActionLink("About", "About", "Maps")</a></li>
                            <li><a href="#">@Html.ActionLink("Fans Statistics", "Plugin", "Blog")</a></li>
                            <li><a href="#">@Html.ActionLink("Post Statistics", "PostTreeD3", "Tree")</a></li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <!--Intro-->
    <div class="text-center">
        <img src="~/Images/Intro.PNG" class="w3-round" />
    </div>
    <!--Body Content-->
    <div id="content">
        <div id="mainContent">
            @RenderBody()
        </div>
        <aside>
            <section>
                <div class="container">
                    @Html.Action("_SeggPost", "Blog")
                </div>
            </section>
            <section>
                <div class="container">
                    @Html.Partial("_WeatherAPI")
                </div>
            </section>
            <section>
                <header>
                    <h3>Categories</h3>
                </header>
                <ul>
                    <li><a href="#">Lorem ipsum dolor</a></li>
                    <li><a href="#">Sit amet consectetur</a></li>
                    <li><a href="#">Adipisicing elit sed</a></li>
                </ul>
            </section>
            <section>
                <header>
                    <h3>Archives</h3>
                </header>
                <ul>
                    <li><a href="#">December 2008</a></li>
                    <li><a href="#">January 2009</a></li>
                    <li><a href="#">February 2009</a></li>
                    <li><a href="#">March 2009</a></li>
                </ul>
            </section>             
        </aside>
    </div>
    <!--Footer-->
    <div style="background-color:black;color:#fff;margin-top:70px;padding:60px;">
        <div class="container">
            <footer class="w3-row-padding w3-padding-32">
                <div class="w3-third">
                    <h3>About</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la</p>
                </div>
                <div class="w3-third">
                    <h3>Blogroll</h3>
                    <ul>
                        <li><a href="#">NETTUTS+</a></li>
                        <li><a href="#">FreelanceSwitch</a></li>
                    </ul>
                </div>
                <div class="w3-third">
                    <h3>Popular</h3>
                    <ul>
                        <li><a href="#">This is the title of a blog post</a></li>
                        <li><a href="#">Lorem ipsum dolor sit amet</a></li>
                        <li><a href="#">Consectetur adipisicing elit, sed do eiusmod</a></li>
                    </ul>
                </div>
            </footer>
        </div>
    </div> 

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

ShauliBlogProject/Views/Shared/_SeggPost.cshtml
@model ShauliBlogProject.Models.Post

<h3 style="font-style:oblique">May be of interest:</h3>
<h4><a href="@Href("~/Blog/Details/" + Model.PostID)">@Model.Title</a></h4>
<p>By @Model.Author on @Model.postDate.ToString()</p>

ShauliBlogProject/Views/Shared/_WeatherAPI.cshtml
<div id="w-btn" class="btn btn-block">Click to see the<br /> weather in the city of Shauli</div>
<b><span id="name"></span> <br /></b>
<span id="temp"></span> <br />
<span id="humidity"></span> <br />
<span id="desc"></span>

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script>
    $(document).ready(function () {
        $("#w-btn").click(function () {
            $.get("http://api.openweathermap.org/data/2.5/weather?q=TelAviv&APPID=e90192ee2d111e992bab287e8d3e8869&units=imperial", function (response) {
                $("#name").text(response.name);
                $("#temp").text("The Tempature is: " + Math.round((response.main.temp - 32) * (5 / 9)) + "℃");
                $("#humidity").text("Humidity: " + response.main.humidity);
                $("#desc").text("Description: " + response.weather[0].description);
                $("#w-btn").hide();
                //console.log(response);
            });
        });
    });
</script>

ShauliBlogProject/Views/Shared/_mapError.cshtml
@{
    ViewBag.Title = "Error";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="mainContent">
    <div id="tc_top"></div>
    <div id="tooplate_content">
        <section class="post_box">
            <h4 class="page-header">
                Summary
                <small>Number of Fans per country</small>
            </h4>
            <div id="map_canvas" style="width: 480px; height: 480px;margin-left: 140px;margin-bottom: 50px;"></div>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBoAjbWMGtd8VinKxGl8291xEd0pWWX_Ns&?sensor=false"></script>
            <script type="text/javascript">
                function initialize() {

                    var mapOptions = {
                        center: new google.maps.LatLng(31.3913989, 35.3259869),
                        zoom: 7,
                        mapTypeId: google.maps.MapTypeId.ROADMAP
                    };

                    //Initial-map
                    var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
                    @{ 
                        <text> addMarkerOffice(31.9651589, 34.782334);</text>
                        <text> addMarkerOffice(32.033168, 34.7580752); </text>
                    }

                    @{ 
                        <text> addMarker(31.9651589, 34.782334); </text>
                        <text> addMarker(31.9421398, 34.8397339); </text>
                    }

                    //Add-marker
                    function addMarker(x, y) {
                        var location = new google.maps.LatLng(x, y);
                        var marker = new google.maps.Marker({
                            position: location,
                            map: map,
                        });
                        marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')
                    }

                    //Add-marker office
                    function addMarkerOffice(x, y) {
                        var location = new google.maps.LatLng(x, y);
                        var marker = new google.maps.Marker({ position: location, map: map, });
                        var imagePath = 'https://www.google.co.il/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjDjMCipa_WAhXHnRoKHblNCWwQjRwIBw&url=https%3A%2F%2Fdevelopers.google.com%2Fmaps%2Fget-started%2F&psig=AFQjCNHJSi_lbFKMFzwCXwTODDAauDlwYA&ust=1505843216230634';
                        marker.setIcon(imagePath)
                    }
                }google.maps.event.addDomListener(window, 'load', initialize);
            </script>
        </section>
    </div>
</div>